### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nvuhna** [MerchantPug/toomanyorigins#11]
it always says this
![image](https://user-images.githubusercontent.com/83992811/117742410-b69e2c80-b1d2-11eb-91ab-63eec7f82ed1.jpg) pls help

**Comment by SpinnyBoiii** [comment]
might wanna show the crash report as well m8

**Comment by MerchantPug** [comment]
I think I know what it is as people on my Discord server have reported something similar to this but I do need more information to actually know so please provide crashlog

**Comment by MerchantPug** [comment]
Resolved through Discord.
