### ISSUE TITLE
Not a major issue, but...

### ISSUE THREAD

**Issue by Cookie-Kurokami** [MerchantPug/toomanyorigins#12]
Any chance you plan on adding compatibility for custom furnaces to the dragon breath? If not, do you have any idea how I might be able to do so myself?

**Comment by MerchantPug** [comment]
From the wiki page:
* Dragonborn gets which of the two abilities are used from the lightable tag. If you have any modded furnaces/campfires you are able to add them to the blocktag `toomanyorigins/tags/blocks/lightable`

**Comment by MerchantPug** [comment]
Just create a datapack with your additions to the blocktag and upload it to the world folder.

**Comment by Cookie-Kurokami** [comment]
I got it working with the Furnaces from BetterNether and BetterEnd, but I can't seem to do the same with Fabric Furnaces. The sound effect plays, my character sticks their arm out as though lightning the furnace, and the cooldown bar for furnace lighting appears rather than the one for the dragon breath attack, but for some reason the furnaces from Fabric Furnaces just won't light. Why is that?

**Comment by MerchantPug** [comment]
> I got it working with the Furnaces from BetterNether and BetterEnd, but I can't seem to do the same with Fabric Furnaces. The sound effect plays, my character sticks their arm out as though lightning the furnace, and the cooldown bar for furnace lighting appears rather than the one for the dragon breath attack, but for some reason the furnaces from Fabric Furnaces just won't light. Why is that?

The light furnace power currently only detects vanilla furnaces and furnaces that the extend vanilla code. My guess is that fabric furnaces don't use this vanilla code.

**Comment by MerchantPug** [comment]
They extend this vanilla code but they don't use everything vanilla furnaces do so that's why they don't work.

I may make a compatibility fix for it but I'm not certain on whether I'm going to do this.

**Comment by Cookie-Kurokami** [comment]
Well, I'm glad that you're at least considering it. The Fabric Furnaces are amazing on their own so I can live without a compatibility patch, but I'd be very grateful if you managed to create one.

**Comment by MerchantPug** [comment]
Okay so update: They don't extend vanilla code at all. It's just that furnace lighting is kinda weird rn.

**Comment by MerchantPug** [comment]
Alright so unfortunately I will not be adding Fabric Furnaces compatibility.

My dev environment crashes because Fabric Furnaces can't find a required class from AutoConfig (a no longer supported mod), my guess is that this and Cloth Config don't want to work with each other.

So unfortunately since the game is unable to open, this will not be a possibility until Fabric Furnaces is updated. It could be updated once 1.17 comes around so I'm hoping for that.

**Comment by Cookie-Kurokami** [comment]
On July 23rd, 2021 you added compatibility with Fabric Furnaces—allowing Dragonborn's dragon breath to light the furnaces added by that mod. I recall even using the mod during that time and the feature functioning perfectly.
![image](https://user-images.githubusercontent.com/66750372/198866544-f7f87961-e69b-4015-b119-a8ac595180a5.png)
However, I'm attempting to do this now and it's yielding the same results as it did last year on May 18th when I made this thread. I added the furnaces to the lightable.json file and everything. Has this compatibility been removed?

**Comment by ChrysanthCow** [comment]
Yes, unfortunately this compatibility has been removed.

**Comment by ChrysanthCow** [comment]
I didn't have the proper knowledge on how to bring the project into a dev environment when there's no maven upload or motivation to continue working with a mod I kinda don't really care about (this is just personal opinions)

**Comment by ChrysanthCow** [comment]
Another thing is that I'm unsure how often the creator even looks at the mod nowadays, and so, I'm going to say that I have no plans to readd the compat as of rn.

I also just have more important things to work on involving the mod.
