### ISSUE TITLE
Dragonborn's light up Brewing Stand skill

### ISSUE THREAD

**Issue by Satrianx** [MerchantPug/toomanyorigins#13]
As with furnaces and campfires, however, with brewing stand, thus allowing the creation of potions without fuel :)

![2021-05-28_16 12 41](https://user-images.githubusercontent.com/84991276/120031765-9c848c80-bfcf-11eb-8efc-168c82283230.png)

**Comment by Satrianx** [comment]
pls <3

**Comment by MerchantPug** [comment]
I'll be bringing this up with the others

**Comment by Satrianx** [comment]
Thanks so much, it's wonderful to have an answer

**Comment by MerchantPug** [comment]
Late response but feature has been confirmed for 0.2.0

**Comment by Satrianx** [comment]
That's so perfect, thx for the attention
