### ISSUE TITLE
Withered Plants

### ISSUE THREAD

**Issue by maskichu** [MerchantPug/toomanyorigins#14]
I've been trying to get into my friends and my own server, and every single time I get on, I get the same message, 

Registry remapping failed: received ID map from minecraft:block contains IDs unknown to user!
- Toomanyorigins:withered_potatoes
- Toomanyorigins:withered_pumpkin_stem
- Toomanyorigins:withered_pumpkin
- Toomanyorigins:withered_carrots

...and so on with all the other plants. I've tried different versions, redownloading fabric api and fabric launcher, I've tried redownloading or restarting the server, I've tried different mod versions, and I've tried making new servers. None of these worked. I'm so baffled and confused. I really want to play the mod, but it won't let me in. I don't know if this extra information will help, but I use a windows HP laptop, version 8.1, the minecraft version we use is 1.16.5. Please help.

**Comment by MerchantPug** [comment]
I've gotten messages about this and I'm unsure on what's up myself.

**Comment by MerchantPug** [comment]
Okay so could you first check if you've got the mod on both your client and server and that these two are both the same version.

I'm just asking this to make sure you know that addons don't work like Origins Datapacks

**Comment by MerchantPug** [comment]
Inactive thread, solution above
