### ISSUE TITLE
enhancement idea for the undead resistance power

### ISSUE THREAD

**Issue by SpinnyBoiii** [MerchantPug/toomanyorigins#15]
i noticed the visual effect being active even when not at half or less health, would maybe be a bit better of a visual que for pvp in multiplayer if the effect only manifests when actually immune to projectiles

**Comment by MerchantPug** [comment]
That definitely shouldn't be happening.

**Comment by SpinnyBoiii** [comment]
ah, i apologize.
a mate of mine had sent me an editted version and it turns out that the skill was editted, he'd made it into an origins:multiple power(it also giving inverted shaders like enderman spectator when active), which apparently causes the shield effect to be active fulltime(since this was pretty interesting, i tested if it was the same with the effect ambience, particles and icon, which did still work)
