### ISSUE TITLE
LAN world crash

### ISSUE THREAD

**Issue by ChubbsWasTaken** [MerchantPug/toomanyorigins#18]
Hiss-Kin doesnt work on LAN worlds, whenever the ability is used it kicks the user. i have no idea why, using the latest version on 1.17

**Comment by MerchantPug** [comment]
Huh okay, can't say I expected this.

May you please send logs so I can check what's up?

**Comment by MerchantPug** [comment]
I tested this out in my test world and I couldn't replicate it.

**Comment by MerchantPug** [comment]
Inactive thread
