### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by seungamn** [MerchantPug/toomanyorigins#3]
The game crashes when I load this mod. All the other mods are working just not this one

**Comment by MerchantPug** [comment]
May I have a modlist and crashlogs?

**Comment by seungamn** [comment]
<img width="1240" alt="Screen Shot 2021-04-17 at 8 31 29 pm" src="https://user-images.githubusercontent.com/82637809/115110002-788b5f80-9fbc-11eb-8186-4e629c0ee098.png">
<img width="589" alt="Screen Shot 2021-04-17 at 8 32 52 pm" src="https://user-images.githubusercontent.com/82637809/115110012-7de8aa00-9fbc-11eb-9b5d-ccd6a060c983.png">

**Comment by seungamn** [comment]
the other origins apart from 'toomanyorigins' are working fine, this only happens when I add this specific mod pack

**Comment by MerchantPug** [comment]
I'm not denying that the crash is there but I'm going to need the crash logs if I am to do anything.
You can find this in the game directory's crash reports folder.

**Comment by MerchantPug** [comment]
You need to update Origins to 0.7.0
