### ISSUE TITLE
idea for Dragonborn debuff: unable to set spawn

### ISSUE THREAD

**Issue by vuatson** [MerchantPug/toomanyorigins#34]
Dragonborns would be able to sleep in beds, but they would be unable to set their spawn using a bed or respawn anchor - they can only respawn at worldspawn. (Possible addition: when they die in the End they automatically respawn on the main End island.)

My friends and I are looking for some extra origins to start a new Origins server, and Dragonborn looks really fun but a bit OP. This occurred to me as an interesting way to balance it out! It would reflect how the actual Dragon is bound to one location and it would make an interesting challenge to play with.

**Comment by MerchantPug** [comment]
Well lucky for you.

I'm planning on reworking the arrow debuff into something more interesting next update.
Hopefully that'll balance it out a bit.

**Comment by MerchantPug** [comment]
And while I think this is a nice idea, it'd bump Dragonborn up to an Impact II which is something I kinda don't want.

**Comment by MerchantPug** [comment]
I'm also most likely going to remove the enchant piercing from the fireball because it's unrivalled by anything else in the game.

**Comment by MerchantPug** [comment]
Basically future Dragonborn changes for next update.

**Dragonborn**
- Dragon Fireball AoE is no longer considered unblockable (pierces through protection enchants)
- Removed Weak Point
- Added Loose Scales. You take more damage when struck from behind
- Renamed Zenith Scales to Zenith Dragonhide (to prevent confusion when describing the new power's name)

**Comment by MerchantPug** [comment]
Tho feel free to modify Dragonborn yourself if you don't see how it is currently fit for your own experience.
