### ISSUE TITLE
Primary Abilities not working

### ISSUE THREAD

**Issue by QuickSlash71** [MerchantPug/toomanyorigins#37]
As the title suggests, primary abilities for Origins of this mod specifically simply don't work. No crashing or anything, just nothing happens. I've checked my controls/keybinds and changed them to see what would work but no luck. I've even tried switching mod versions. The other origin mods I'm using are: Origins, ExtraOrigins, MobOrigins, Consular's Origins, Goat Origin, Origins: Classes, Environmental Armor. I have used these mods in conjunction in the past and they have worked perfectly fine.

**Comment by MerchantPug** [comment]
I'm unsure why this'd be the case.

**Comment by MerchantPug** [comment]
Will test at a later date and see what's up.

**Comment by ChrysanthCow** [comment]
Closed due to inactivity on my end, sorry.
