### ISSUE TITLE
Action wheel for figura support

### ISSUE THREAD

**Issue by AmburLoaf** [MerchantPug/toomanyorigins#38]
the title might be a bit misleading, but this mod prevents the use of figura's action wheel. Because of how your mod works, if the overlay isn't open, the mouse will stay locked. However, this also affects the figura mod's action wheel, as now i cannot access it due to not being able to move the mouse.

**Comment by MerchantPug** [comment]
Which overlay? I don't think I included any overlays

**Comment by AmburLoaf** [comment]
my bad i was looking at the wrong mod, it was the extraorigins mod

**Comment by MerchantPug** [comment]
I've brought this issue up on the creator's Discord and it'll hopefully be fixed sometime.
