### ISSUE TITLE
Rework Existing Origins

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/toomanyorigins#39]
I've detailed that I'm doing this through my Discord server, however I am posting this issue this to give non Discord users some notice.

## Please join the [Discord](https://discord.gg/UBfEjsANNz) to talk about this.

**Comment by ChrysanthCow** [comment]
There will not be any new Origins until the existing ones are made up to scratch with my current thoughts on game design. I also don't plan on adding many more new origins if any.

**Comment by MerchantPug** [comment]
Thread locked, please discuss the individual Origins in their respective Issues.

**Comment by ChrysanthCow** [comment]
Finished Hiss-kin and Swarm reworks. Can be downloaded through my Discord server.

**Comment by ChrysanthCow** [comment]
Don't read the issues above. They are outdated to my current game design opinions.

**Comment by ChrysanthCow** [comment]
Withered rework is finished but not final and has been released on CurseForge, Modrinth and GitHub as a beta/prerelease alongside the Hiss-kin and Swarm reworks.

**Comment by ChrysanthCow** [comment]
Dragonborn and Hare reworks have been finished and released for mc versions 1.19.2 and 1.20.x
