### ISSUE TITLE
Withered Rework

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/toomanyorigins#40]
## Problems with Existing Design
Withered as an Origin is my least favourite origin in the entire package.

The powers are entirely based off two mobs and there's not much creativity in the powers of it. Which goes against the base mod's design, something that this mod is trying to emulate in its own way.

It also has compatibility issues with other mods due to the Black Thumb con and I find it's counter intuitive to ask people to add their modded crops to a tag.

## Proposed Concept
Withered is going to be getting a complete rework.

Instead of filling the same roles as Blazeborn but with more PvP focused powers, it will instead become a more hunting focused nether origin. 

It will not be getting any changes that make it more tied to the nether unless Blazeborn does, this is so the origin isn't just a better choice compared to what its meant to sidegrade.

**Comment by PlexoftV** [comment]
oh lol I just saw this after posting a similar suggestion, nice.

**Comment by PlexoftV** [comment]
I would also recommend not completely removing its functionality in the overworld, maybe just buff it in the nether as opposed to nerfing it in the overworld.

**Comment by MerchantPug** [comment]
> I would also recommend not completely removing its functionality in the overworld, maybe just buff it in the nether as opposed to nerfing it in the overworld.

I wouldn't **completely** remove functionality in the overworld, I feel I'd probably just have to adjust once blazeborn gets its thing.

Either way there's two sides to the "How do we make an origin have incentive to at least partially base in the nether" argument

**Comment by MerchantPug** [comment]
The original one.

**Comment by PlexoftV** [comment]
sorry I dont know what you mean by

"It will not be getting any changes that make it more tied to the nether until Blazeborn does"  

Do you mean the original creator of the origins mod is updating the blazeborn?

**Comment by MerchantPug** [comment]
> sorry I dont know what you mean by
> 
> "It will not be getting any changes that make it more tied to the nether until Blazeborn does"
> 
> Do you mean the original creator of the origins mod is updating the blazeborn?

Someday potentially.

The only change would be that it gets more incentive to stay in the nether. Otherwise I think it's fine as is

**Comment by ChrysanthCow** [comment]
Update to the above before I close this, I was very misinformed in terms of Blazeborn.

That will not be getting any changes as Apace feels that nether incentive is more something that origins wouldn't be able to change and moreso feels that it's due to the lack of content in the nether when compared to the overworld.
