### ISSUE TITLE
Dragonborn Rework

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/toomanyorigins#41]
## Problems with Existing Design
Dragonborn has many issues with its current design. 

The whole point of it in current design is it's meant to be a tank, however it does not quite have anything that makes the fact that you're a tank but not actually a tank, you are quite literally a tank. While the Loose Scales change may have helped this in the eyes of many, all it does is make you incompatible for fights against groups. On top of this, Dragonborn's mere concept interferes with what Shulk is but it does a poorer job at it.

Additionally brewing stand lighting is not going to stay as it fucks with Minecraft progression a little too much for my liking.

```diff
- Still does not have flight.
```
*The above is a joke, I will NOT be adding flight, please don't ask.*

## Proposed Concept
Dragonborn is getting a total rework too. The idea behind the rework is to make your fireball more impactful to your gameplay style, currently it feels like a damage output that just happens.

The fireball will become a zoning tool and will help you play offensively or play defensively. You will excel in close quarters combat, with your positioning being a huge part of the origin.

**Comment by ChrysanthCow** [comment]
Closing this issue due to datedness.
