### ISSUE TITLE
Hiss-kin Rework

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/toomanyorigins#42]
## Problems with Existing Design
Hiss-kin is honestly pretty good although there are some bad things about it.

Explosion Immunity is horrible to fight against in some playstyles.
The Charged status effect (which is ultimately something I added for fun) prioritises flavour over gameplay in that the speed boost from it is not a good addition.

Slowness isn't a great downside. Hiss-kin has a better use of slowness than most origins in that in a way it gets you to jump and use your rocket jump but on the other hand, slowness just isn't fun to play with.

Ailurophobia is just completely uninspired.

## Proposed Concept
Hiss-kin honestly doesn't need many changes. Make the main traits of it center around risking yourself. The rocket jump damaging yourself is pretty good for this, however there could be a minor downside (doesn't need to be large as the rocket jump hurting you is honestly fairly large) that plays into this too. Ailurophobia should be more relevant to what the origin is and you could potentially even use it to play around this other downside. Explosion Immunity should be changed to reduced explosion damage.

**Comment by ChrysanthCow** [comment]
If you are interested in discussing the reworked origins, you are available to through my Discord.
