### ISSUE TITLE
Hare Rework

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/toomanyorigins#44]
## Problems with Existing Design
TooMany™

Hare is clunky to play. 
Keeping speed is way too punishing and running around feels wrong.

## Proposed Concept
Hare will become an origin about travelling on foot. Elytra should gain a different purpose instead of its current use. A new downside would be that it's harder to stop depending on the speed you've built up. The active power is entirely unnecessary with the carrot changes and certain actions should not slow you down (namely eating).

If the bunny hopping mechanics were refined to be less clunky then the origin should feel pretty good.

**Comment by ChrysanthCow** [comment]
Closing this issue due to datedness.
