### ISSUE TITLE
small hisskin buff

### ISSUE THREAD

**Issue by hiimpranav** [MerchantPug/toomanyorigins#47]
I feel like hisskin is pretty well balanced as of now, but on top of the slowness the constant eating required to heal is a real resource drain, so I was thinking of maybe a small passive regen would be useful, similar to Octane's passive in apex legends.

**Comment by MerchantPug** [comment]
Hiss-kin is getting a rework in the future. I'm axing the current cons and replacing them with new ones.

I'm actually pretty open minded to this suggestion tho, I never thought of food drain being an issue with the origin.

I most likely won't be adding anything of this regard to the origin as I wish to keep a risk to using your powers but I'm honestly not against this suggestion as a whole.

**Comment by ChrysanthCow** [comment]
Ho, ho, ho. Remember when I said slowness wouldn't be a thing anymore?

Well, it's now stronger in the final cut to encourage rocket jump usage but I opted to remove the cat slowness instead. Nothing was really done about the eating situation as I didn't feel it was too much of an issue, I wanted to moreso focus on the general playability of the origin.
