### ISSUE TITLE
Idea for the Withered Origin 

### ISSUE THREAD

**Issue by PlexoftV** [MerchantPug/toomanyorigins#48]
I love how simplistic the Withered origin currently is, but I feel that it could use a bit more spice in order to make it more unique,

Idea:
Pros
Give it permanent fire resistance (as withers and wither skeletons have)
Have ability to shoot wither skulls 

OR 

Give it a primary ability which has a 5 minute cooldown (can be changed) and when you activate it you slowly _wither_ away, but you gain the ability to hover as the wither can, and shoot wither skulls with a short cooldown (5 secondish) This form can last until you are half a heart, but it can only last for up to 1 minute, to prevent it from being too op combined with healing items such as regen potions or gapples

Cons:
Piglin Problems
Piglins will refuse to barter with you

Sword Supremacy
You do less damage with bows/crossbows  or you cant use bows (since wither skeletons cannot use bows)
You also do less damage with Axes and Tridents because you are used to wielding a sword

Brittle Bones
You take 1.2% more damage from fall damage

Neutral:
All potion effects are inverted

Thank you for reading!

**Comment by MerchantPug** [comment]
I think I'll respond to this by saying what would these pros and cons contribute to the gameplay of the origin?

Not to mention that fire immunity would be invalidating of Blazeborn. Hovering is invalidating of Swarm if implemented in the same way whilst flight has to be placed on an origin extremely cautiously.

I just really don't want to give the origin wither skulls, like the Origin =/= mob philosophy is coming into play here.

I know you've responded in my rework thread (I think?).
