### ISSUE TITLE
Dragon Breath bug(?,idk if done intentionally)

### ISSUE THREAD

**Issue by SpinnyBoiii** [MerchantPug/toomanyorigins#5]
the AoE will disappear as soon as it inflicts even one tick of damage(unsure if this is the case even on an iframed tick), making the 5s duration pretty much neglectible since you'd likely aim for direct hits anyways

**Comment by MerchantPug** [comment]
It is 100% intentional

I also agree that the 5s increase was the worst of the buffs but it's better than nothing tbh, it can at least be used as a zoning tool.
