### ISSUE TITLE
Withered origins crashing my worlds

### ISSUE THREAD

**Issue by Juicylene** [MerchantPug/toomanyorigins#50]
mod version: forge 1.16.5-0.4.2
forge version: 36.2.29

description: Basically the withered race instantly crashes my game whenever i choose it, and the crash logs point out that its due to "Exception in server tick loop".

crash log:
[crash-2022-04-12_17.58.54-server.txt](https://github.com/MerchantPug/toomanyorigins/files/8476595/crash-2022-04-12_17.58.54-server.txt)

**Comment by MerchantPug** [comment]
Is it just the Withered Origin?

To me this seems like BYG causing it.

**Comment by Juicylene** [comment]
Just tested it and nah, the normal origins are fine and dont cause any problems, but i've figured that maybe the problem is linked to apugli rather than this mod

**Comment by MerchantPug** [comment]
I would bring this up to the BYG dev, Origins, Apugli and TooManyOrigins have nothing to do with worldgen so I doubt it'd be one of these mods.
