### ISSUE TITLE
non-character in namespace

### ISSUE THREAD

**Issue by articulatememe** [MerchantPug/toomanyorigins#53]
Hi! I keep on getting this same issue when i try to join a server with this mod installed.
<img width="948" alt="Screen Shot 2022-09-09 at 9 11 48 PM" src="https://user-images.githubusercontent.com/113220137/189463040-20cf9b63-4c5e-4c6d-9c6d-59faffe8100d.png">

**Comment by ChrysanthCow** [comment]
Please tell me what datapacks and other addons you have, the issue lies in the server trying to sync its origin data with the client, I doubt it's this mod doing it.

Additionally, what MC version are you on?

**Comment by ChrysanthCow** [comment]
Something I'd also like to check is have you modified any of the TooManyOrigins origins and if so, a broken power there is not a bug regarding this mod.

**Comment by ChrysanthCow** [comment]
~~Okay new thing I'd like to check. Do you have this mod installed on your client?~~

There probably would've been a message booting you out if that were the case...

**Comment by ChrysanthCow** [comment]
I'm boiling this down to a registry desync, which is not really an issue with this mod and moreso an issue of the user not having certain mods on their client that the server has.
