### ISSUE TITLE
Crash on latest version

### ISSUE THREAD

**Issue by nobleRadical** [MerchantPug/toomanyorigins#58]
[crash-2023-01-28_14.37.22-client.txt](https://github.com/MerchantPug/toomanyorigins/files/10528448/crash-2023-01-28_14.37.22-client.txt)

The only mods I have installed are origins and this one.

**Comment by ChrysanthCow** [comment]
Thanks for the report, I'll look into fixing it soon.

**Comment by ChrysanthCow** [comment]
Fixed in v0.7.2+1.19.3
