### ISSUE TITLE
dragonborn not showing up in server??

### ISSUE THREAD

**Issue by JustDylan8480** [MerchantPug/toomanyorigins#70]
when me and my friends started a server, dragonborn just decides not to show up

**Comment by ChrysanthCow** [comment]
What exact version of TooManyOrigins are you on?

**Comment by JustDylan8480** [comment]
1.0.0 for 1.19.3

**Comment by ChrysanthCow** [comment]
That version is a rework that doesn't yet include Dragonborn (it was introduced in beta 13, which'll probably never be supported on 1.19.3).

It may also explain why some of the origins are different to how the page describes them.

You can download 0.9.1 to get the origin.

**Comment by ChrysanthCow** [comment]
https://modrinth.com/mod/toomanyorigins/version/0.9.1+1.19.3-fabric
