### ISSUE TITLE
Faliure to launch after installation

### ISSUE THREAD

**Issue by TabbyNotMe** [MerchantPug/toomanyorigins#79]
When I installed this mod on Forge (app), my launcher failed to open. I tried removing the mod, and it still did not open. I had no issues beforehand, and my friends are not having issues. I also tried opening vanilla and it still did not work. Any idea what I could do? I even tried changing the forge version and using other profiles.

**Comment by ChrysanthCow** [comment]
It sounds like you have a corrupted curseforge launcher. I can't really provide help with that.

I'd try reinstalling.
