### ISSUE TITLE
Draconic Breath server crash

### ISSUE THREAD

**Issue by knapdragon** [MerchantPug/toomanyorigins#87]
Fired a thunder ball at a creeper on fire.

Minecraft version: 1.20.
TooManyOrigins: 1.1.1+1.20.1 (Fabric)

Callstack: [1.20.1 crash report.txt](https://github.com/MerchantPug/toomanyorigins/files/15144117/1.20.1.crash.report.txt)

**Comment by ChrysanthCow** [comment]
Thanks, I'll fix this later.

**Comment by ChrysanthCow** [comment]
This likely happened because the creeper died.

**Comment by ChrysanthCow** [comment]
Anyways, I have since fixed this by making the condition relating to attackers check if the attacker exists.
