### ISSUE TITLE
dragon fireball hit detection suggestion

### ISSUE THREAD

**Issue by SpinnyBoiii** [MerchantPug/toomanyorigins#9]
was testing the change and noticed it not hitting as often as it should, enabled visual hitboxes and noticed that an entity's hurtbox had to be over halfway in the hitbox before taking damage. this makes the visual hitbox of a 3x3 square(and a little bit of height) that the dragon fireball has quite a bit smaller depending on the target's size(against a big slime for example it'd effectively have an AoE size of less than 1x1 block horizontally)

**Comment by SpinnyBoiii** [comment]
mb, not a bug, just noticed lingering potions and enderdragon fireballs have the same problem.
buff suggestion instead.
might want to buff the AoE size a bit seeing as, while they have the same situation, splash/lingering potions and the enderdragon's fireballs have a much bigger AoE(enderdragon's fireballs having like 6x6 blocks on startup and 13x13 blocks in the end, lingering potions starting with 6x6 blocks and, whilst not visible, probably the same for splash potions)

**Comment by MerchantPug** [comment]
Currently Dragonborn's ends at 3x3 blocks, we may increase this radius but I'll have to update the others on this.

**Comment by MerchantPug** [comment]
Okay so the max radius has been increased to 4.5 x 4.5 blocks with the starting radius being half of this.
Thanks for telling us about this oversight that we had no idea about.

**Comment by SpinnyBoiii** [comment]
It was my first time even enabling hitboxes with lingering AoE's, I would've definitely made the assumption myself that hitbox even slightly touching the hurtbox=damage

**Comment by SpinnyBoiii** [comment]
when will this change be implemented btw? noticed its still the same currently

**Comment by MerchantPug** [comment]
The change will be implemented next update. I can't quite make change it in a released update.

**Comment by MerchantPug** [comment]
Added in 0.1.3a
