### ISSUE TITLE
[Fabric/Quilt 1.20.1] Crash when paired with Supplementaries v3.1.0

### ISSUE THREAD

**Issue by BlueIsADude** [MerchantPug/toomanyorigins#90]
Honestly, I dont even know why this happens, why its specifically this mod, or even if its on TooManyOrigins' end or not... but I've been getting COUNTLESS crashes, and have reduced my mods folder to 5 mods (Fabric API, Moonlight Lib, Supplementaries, Origins, and TooManyOrigins), and still it consistently crashes.

To replicate:
1. Create a new world.
2. Pick your preferred origin. It literally doesn't matter what you choose.
3. Grab yourself a Lumisene Bucket.
4. Place it down on the side of a block. The game should now crash, but if it doesn't
5. Destroy the Lumisene by placing a block on it. The game is basically guaranteed to crash at this point.

I have no clue how I whittled it down to these 5 mods, the crash logs dont mention anything about Origins, or even Supplementaries for that matter. And removing TooManyOrigins DOES fix the issue btw. The crash logs do mention something about a FluidloggedCollisionShape, but I'm honestly clueless.

I reported this to the Supplementaries github too btw, if this isnt a TooManyOrigins issue.
[latest.log](https://github.com/user-attachments/files/17638892/latest.log)
[crash-2024-11-05_15.26.54-client.txt](https://github.com/user-attachments/files/17638884/crash-2024-11-05_15.26.54-client.txt)

**Comment by ChrysanthCow** [comment]
1. It is TMO.
2. Please calm down, us developers are only human.
3. I've been meaning to remove part of the confusion with the offending code and fix it eventually, my origins mods are just a huge mental drain for me.

**Comment by BlueIsADude** [comment]
I understand, mod dev is really hard and I'm sorry if I came off as a bit rude.
Please take your time!
